- name: Nginx
  hosts: web
  become: yes

  tasks:
  - name: Install nginx
    apt:
       pkg: nginx
       state: present

  - name: Start service nginx
    become: yes
    service:
          name: nginx
          enabled: yes
          state: started
