- name: PgAdmin
  hosts: elk
  become: yes

  tasks:

  - name: Create the file repository configuration
    shell: curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add

  - name: Import the repository signing key
    shell: sudo sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'

  - name: Install pgadmin4
    apt:
       pkg: pgadmin4
       state: present
